In [99]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report

---

## Split the Data into Training and Testing Sets

### Step 1: Read the `lending_data.csv` data from the `Resources` folder into a Pandas DataFrame.

In [100]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
data_path = Path('Resources/Healthcare-Diabetes.csv')
df = pd.read_csv(data_path)

# Review the DataFrame
df.head(5)

Id  Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0   1            6      148             72             35        0  33.6   
1   2            1       85             66             29        0  26.6   
2   3            8      183             64              0        0  23.3   
3   4            1       89             66             23       94  28.1   
4   5            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

### Step 2: Create the labels set (`y`)  from the “loan_status” column, and then create the features (`X`) DataFrame from the remaining columns.

In [101]:
# Separate the data into labels and features

# Separate the y variable, the labels
y = df['Outcome']

# Separate the X variable, the features
X = df.drop(columns='Outcome')
X =X.drop(columns="Id")




In [102]:
# Review the y variable Series
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [103]:
# Review the X variable DataFrame
X.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

### Step 3: Check the balance of the labels variable (`y`) by using the `value_counts` function.

In [90]:
# Check the balance of our target values
y.value_counts()


Outcome
0    1816
1     952
Name: count, dtype: int64

### Step 4: Split the data into training and testing datasets by using `train_test_split`.

In [91]:
# Import the train_test_learn module
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
# Assign a random_state of 1 to the function
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

---

## Create a Logistic Regression Model with the Original Data

###  Step 1: Fit a logistic regression model by using the training data (`X_train` and `y_train`).

In [92]:
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression

# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
logistic_regression_model = LogisticRegression(random_state=1)

# Fit the model using training data
logistic_regression_model.fit(X_train, y_train)


LogisticRegression(random_state=1)

### Step 2: Save the predictions on the testing data labels by using the testing feature data (`X_test`) and the fitted model.

In [93]:
# Make a prediction using the testing data
predictions = logistic_regression_model.predict(X_test)


### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [94]:
# Print the balanced_accuracy score of the model
accuracy = balanced_accuracy_score(y_test, predictions)
print(f"Balanced accuracy score: {accuracy}")

Balanced accuracy score: 0.7106393218080184


In [16]:
# Generate a confusion matrix for the model
confusion = confusion_matrix(y_test, predictions)
print(f"Confusion matrix:\n{confusion}")

Confusion matrix:
[[402  52]
 [110 128]]


In [25]:
# Print the classification report for the model
classification_rep = classification_report(y_test, predictions)
print(f"Classification report:\n {classification_rep}")

Classification report:
               precision    recall  f1-score   support

           0       0.79      0.89      0.83       454
           1       0.71      0.54      0.61       238

    accuracy                           0.77       692
   macro avg       0.75      0.71      0.72       692
weighted avg       0.76      0.77      0.76       692



In [26]:
coefficients = logistic_regression_model.coef_
coefficients

array([[ 1.17219833e-01,  3.51885741e-02, -1.07355720e-02,
         2.39346376e-03, -1.00005719e-03,  6.99917931e-02,
         1.03134468e+00,  1.55069623e-02]])

---

## Predict a Logistic Regression Model with Resampled Training Data

### Step 1: Use the `RandomOverSampler` module from the imbalanced-learn library to resample the data. Be sure to confirm that the labels have an equal number of data points. 

In [18]:
# Import the RandomOverSampler module form imbalanced-learn
from imblearn.over_sampling import RandomOverSampler

# Instantiate the random oversampler model
# # Assign a random_state parameter of 1 to the model
ros = RandomOverSampler(random_state=1)

# Fit the original training data to the random_oversampler model
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)


In [19]:
# Count the distinct values of the resampled labels data
y_resampled.value_counts()

Outcome
0    1362
1    1362
Name: count, dtype: int64

### Step 2: Use the `LogisticRegression` classifier and the resampled data to fit the model and make predictions.

In [20]:
# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
logistic_regression_resampled = LogisticRegression(random_state=1)

# Fit the model using the resampled training data
logistic_regression_resampled.fit(X_resampled, y_resampled)

# Make a prediction using the testing data
predictions_resampled = logistic_regression_resampled.predict(X_test)


/Users/fjdg/anaconda3/envs/dev/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [21]:
# Print the balanced_accuracy score of the model 
balanced_accuracy = balanced_accuracy_score(y_test, predictions_resampled)
print(f"Balanced accuracy score: {balanced_accuracy}")

Balanced accuracy score: 0.7356087809573169


In [22]:
# Generate a confusion matrix for the model
confusion_resampled = confusion_matrix(y_test, predictions_resampled)
print(f"Confusion matrix:\n{confusion_resampled}")

Confusion matrix:
[[357  97]
 [ 75 163]]


In [23]:
# Print the classification report for the model
classification_report_resampled = classification_report(y_test, predictions_resampled)
print(f"Classification report:\n{classification_report_resampled}")

Classification report:
              precision    recall  f1-score   support

           0       0.83      0.79      0.81       454
           1       0.63      0.68      0.65       238

    accuracy                           0.75       692
   macro avg       0.73      0.74      0.73       692
weighted avg       0.76      0.75      0.75       692



### Step 4: Answer the following question

In [95]:
from sklearn.ensemble import RandomForestClassifier

# Assuming you have your data X and labels y
model = RandomForestClassifier()
model.fit(X, y)

# Access feature importances
importances = model.feature_importances_

In [96]:
importances

array([0.34350868, 0.25315625, 0.20350172, 0.19983335])

In [97]:
from sklearn.ensemble import GradientBoostingClassifier

# Assuming X_train, y_train are your training features and labels
model = GradientBoostingClassifier()
model.fit(X_train, y_train)

GradientBoostingClassifier()

In [98]:
predictions = GradientBoostingClassifier.predict(X_test)

accuracy = balanced_accuracy_score(y_test, predictions)
print(f"Balanced accuracy score: {accuracy}")

TypeError: GradientBoostingClassifier.predict() missing 1 required positional argument: 'X'

In [104]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Assuming X and y are your features and labels respectively
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Support Vector Machines (SVM)
from sklearn.svm import SVC
svm_model = SVC()
svm_model.fit(X_train, y_train)
svm_predictions = svm_model.predict(X_test)
svm_accuracy = accuracy_score(y_test, svm_predictions)
print("SVM Accuracy:", svm_accuracy)

# K-Nearest Neighbors (KNN)
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier()
knn_model.fit(X_train, y_train)
knn_predictions = knn_model.predict(X_test)
knn_accuracy = accuracy_score(y_test, knn_predictions)
print("KNN Accuracy:", knn_accuracy)

# Naive Bayes
from sklearn.naive_bayes import GaussianNB
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)
nb_predictions = nb_model.predict(X_test)
nb_accuracy = accuracy_score(y_test, nb_predictions)
print("Naive Bayes Accuracy:", nb_accuracy)

# Decision Trees
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, y_train)
dt_predictions = dt_model.predict(X_test)
dt_accuracy = accuracy_score(y_test, dt_predictions)
print("Decision Tree Accuracy:", dt_accuracy)

# Random Forest
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)
rf_predictions = rf_model.predict(X_test)
rf_accuracy = accuracy_score(y_test, rf_predictions)
print("Random Forest Accuracy:", rf_accuracy)

# Gradient Boosting Machines (GBM)
from sklearn.ensemble import GradientBoostingClassifier
gbm_model = GradientBoostingClassifier()
gbm_model.fit(X_train, y_train)
gbm_predictions = gbm_model.predict(X_test)
gbm_accuracy = accuracy_score(y_test, gbm_predictions)
print("GBM Accuracy:", gbm_accuracy)

# Logistic Regression
from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression()
lr_model.fit(X_train, y_train)
lr_predictions = lr_model.predict(X_test)
lr_accuracy = accuracy_score(y_test, lr_predictions)
print("Logistic Regression Accuracy:", lr_accuracy)



SVM Accuracy: 0.7689530685920578
KNN Accuracy: 0.8646209386281588
Naive Bayes Accuracy: 0.7689530685920578
Decision Tree Accuracy: 0.98014440433213
Random Forest Accuracy: 0.9819494584837545
GBM Accuracy: 0.8808664259927798
Logistic Regression Accuracy: 0.7743682310469314


/Users/fjdg/anaconda3/envs/dev/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
